### ISSUE TITLE
Compatibily with Tensorflow 1.13.x

### ISSUE THREAD

**Issue by HugoDel** [barisozmen/deepaugment#29]
I've just discovered your projet and I would like to add it in my ML pipeline using Tensorflow 1.13.1 but the requirement of my projet doesn't match yours. Is it planned to support an upper version of Tensorflow ?

Thanks !

**Comment by monkeyDemon** [comment]
The author just uses tensorflow to build some basic models, so I don't think the tensorflow version matters.
I have run the code on Python2.7 and tensorflow1.12.0.
After modifying some grammatical errors caused by change Python version from 3 to 2，I run the code successfully.
In addition, I also encountered some problems caused by  function transform()  in augmenter.py，see https://github.com/barisozmen/deepaugment/issues/30#issue-505127289
I don't know if this issue is due to Python version conversion or my misuse. 
Hope to discuss with you.

**Comment by HugoDel** [comment]
It's working with TF 1.13, thanks!
